### ISSUE TITLE
Licenses

### ISSUE THREAD

**Issue by rparundekar** [chensonglu/LPD-indirect-direct#1]
👋 Very interesting work, (I read your paper as well) @chensonglu ! Do you plan to have a license file on this repo? e.g. MIT License, etc. ?

**Comment by rparundekar** [comment]
Could you please add the license file (whichever one you choose)

**Comment by chensonglu** [comment]
@rparundekar Thanks for your interest. I just added an MIT license.

**Comment by rparundekar** [comment]
You're the best! Thank you!
