### ISSUE TITLE
ModuleNotFoundError: No module named 'roi_align',

### ISSUE THREAD

**Issue by Amireux52** [chensonglu/LPD-indirect-direct#3]
ModuleNotFoundError: No module named 'roi_align',请问这个怎么解决？谢谢了

**Comment by chensonglu** [comment]
@chenxinhe1 Please install RoIAlign following https://github.com/longcw/RoIAlign.pytorch.

**Comment by chensonglu** [comment]
@chenxinhe1 首先git clone https://github.com/longcw/RoIAlign.pytorch.git，然后命令行cd到这个文件中，之后执行python setup.py install和./test.sh，注意使用python3，这样我的代码应该就可以运行了
